language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libcajun-dev 
    - libssl-dev

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 99

script:
  - ./autogen.sh
  - ./configure
  - make -j3 distcheck || (cat gg-0.01/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:RFEz0IvxWUHbHFan10UNb3Qo
