language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libssl-dev
    - libcap-dev
    - libkeyutils-dev

before_script:
  - sudo add-apt-repository -y ppa:sfouladi/protobuf-backports
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler libprotobuf-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - pip install --user protobuf

script:
  - ./autogen.sh
  - ./configure --enable-sanitize
  - make -j3 distcheck || (cat gg-0.01/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:RFEz0IvxWUHbHFan10UNb3Qo
