language: cpp
sudo: required
services: docker

git:
  depth: 3
  submodules: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libssl-dev
    - libcap-dev
    - libkeyutils-dev
    - libncurses5-dev

before_script:
  - sudo add-apt-repository -y ppa:sfouladi/protobuf-backports
  - sudo -E add-apt-repository -y 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler libprotobuf-dev
  - sudo apt-get install -y --allow-unauthenticated libboost-dev=1.62.0.1 libboost-filesystem-dev=1.62.0.1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99

script:
  - ./fetch-toolchain.sh
  - ./autogen.sh
  - ./configure --enable-sanitize
  - make -j3 distcheck || (cat gg-0.01/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:RFEz0IvxWUHbHFan10UNb3Qo
